{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tungbo.gradleplugin",
    "module": "gradleplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradleplugin-1.0.0.jar",
          "url": "gradleplugin-1.0.0.jar",
          "size": 1592,
          "sha512": "6300d73bf5990323e4ca83c291894d5d24ab7a5fa7c36c7e687706bbf910f2d81288147745c1cbf9f5bedcff17b8a54f9f9b5cc08c1dc689f9060cf218e9cec3",
          "sha256": "86dadbda89b0bffeff6f21a52ff2cdf4c2a0c24b820fa587e94456aa2ad1149f",
          "sha1": "e45024a9852a912ec0e8503f1fed0f0548faf6e1",
          "md5": "10e83f38e70a5cdffe0d13b616c07a53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradleplugin-1.0.0.jar",
          "url": "gradleplugin-1.0.0.jar",
          "size": 1592,
          "sha512": "6300d73bf5990323e4ca83c291894d5d24ab7a5fa7c36c7e687706bbf910f2d81288147745c1cbf9f5bedcff17b8a54f9f9b5cc08c1dc689f9060cf218e9cec3",
          "sha256": "86dadbda89b0bffeff6f21a52ff2cdf4c2a0c24b820fa587e94456aa2ad1149f",
          "sha1": "e45024a9852a912ec0e8503f1fed0f0548faf6e1",
          "md5": "10e83f38e70a5cdffe0d13b616c07a53"
        }
      ]
    }
  ]
}
